Repository sentouki/Memory-Game, pull requests merged in 2021-09, with the labels that each got.

#22 fix x button click, add text to README
  README.md
  main/index.html
Labels: bug

#25 Added new sound for matched cards
  js/sketch.js
  sounds/README.md
  sounds/flip.mp3
  sounds/flip.ogg
  sounds/flip2.wav
  sounds/flip3.mp3
  sounds/match.mp3
Labels: bug, enhancement

#26 [WIP] fix mobile placement
  css/style.css
  index.html
Labels: bug, enhancement

#28 Improved performance
  css/modal.min.css
  css/style.min.css
  images/animals/1.png
  images/animals/1.webp
  images/animals/10.png
  images/animals/10.webp
  images/animals/11.png
  images/animals/11.webp
  images/animals/12.png
  images/animals/12.webp
  images/animals/13.png
  images/animals/13.webp
  images/animals/14.png
  images/animals/14.webp
  images/animals/15.png
  images/animals/15.webp
  images/animals/16.png
  images/animals/16.webp
  images/animals/17.png
  images/animals/17.webp
  images/animals/18.png
  images/animals/18.webp
  images/animals/19.png
  images/animals/19.webp
  images/animals/2.png
  images/animals/2.webp
  images/animals/3.png
  images/animals/3.webp
  images/animals/4.png
  images/animals/4.webp
  images/animals/5.png
  images/animals/5.webp
  images/animals/6.png
  images/animals/6.webp
  images/animals/7.png
  images/animals/7.webp
  images/animals/8.png
  images/animals/8.webp
  images/animals/9.png
  images/animals/9.webp
  index.html
  js/card.min.js
  js/helpers.min.js
  js/modal.min.js
  js/p5.js
  js/p5.min.js
  js/p5.sound.min.js
  js/sketch.js
  js/sketch.min.js
Labels: enhancement
